# Generated by Django 5.0.6 on 2024-06-26 20:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("issues", "0001_change_constraints"),
        ("issues", "0002_change_structure"),
        ("issues", "0003_change_structure_3"),
        ("issues", "0004_change_structure_4"),
        ("issues", "0005_create_status_field"),
    ]

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="IssueOwner",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("pts", models.IntegerField(default=0, verbose_name="UserPoints")),
            ],
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("i_name", models.CharField(default="New Issue", max_length=50)),
                (
                    "i_desc",
                    models.CharField(blank=True, default="No desc", max_length=512),
                ),
                (
                    "ugc_rating",
                    models.IntegerField(
                        choices=[
                            (1, "Misc"),
                            (2, "Non Ugn"),
                            (3, "Essential"),
                            (4, "Ugn"),
                            (5, "High Ugn"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "dif_rating",
                    models.IntegerField(
                        choices=[
                            (1, "Very Easy"),
                            (2, "Easy"),
                            (3, "Medium"),
                            (4, "Hard"),
                            (5, "Very Hard"),
                        ],
                        default=2,
                    ),
                ),
                (
                    "recur",
                    models.CharField(
                        choices=[("Recurring", "R"), ("One-Time", "O")],
                        default="One-Time",
                        max_length=10,
                    ),
                ),
                (
                    "i_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="issue_date"
                    ),
                ),
                (
                    "s_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="solved_date"
                    ),
                ),
                (
                    "d_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deadline"
                    ),
                ),
                (
                    "o_uid",
                    models.ForeignKey(
                        default=2,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owner_uid",
                        to="issues.issueowner",
                    ),
                ),
                (
                    "i_status",
                    models.BooleanField(
                        choices=[(False, "Not solved"), (True, "Solved")],
                        default=False,
                        verbose_name="Solve status",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IssueRec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "i_id",
                    models.ForeignKey(
                        default=2,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="issues.issue",
                    ),
                ),
                (
                    "s_uid",
                    models.ForeignKey(
                        default=2,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solver_uid",
                        to="issues.issueowner",
                    ),
                ),
                (
                    "i_cost",
                    models.FloatField(
                        default=0.0, max_length=50, verbose_name="issue_cost"
                    ),
                ),
            ],
        ),
    ]
