# Generated by Django 5.0.6 on 2024-06-26 20:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0001_merged_issues"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issue",
            name="recur",
        ),
        migrations.AddField(
            model_name="issueowner",
            name="profile_img",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.CreateModel(
            name="IssueComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "c_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="comment_date"
                    ),
                ),
                (
                    "commenter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commenter",
                        to="issues.issueowner",
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_issue",
                        to="issues.issue",
                    ),
                ),
            ],
        ),
    ]
