# Generated by Django 5.0.6 on 2024-06-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0002_profilepic_and_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="issuecomment",
            name="c_cont",
            field=models.CharField(default="No comment", max_length=512),
        ),
        migrations.AlterField(
            model_name="issueowner",
            name="profile_img",
            field=models.ImageField(
                blank=True, default="default.jpg", null=True, upload_to=""
            ),
        ),
    ]
