# Generated by Django 4.2.7 on 2024-06-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("issues", "0002_change_structure"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issue",
            name="i_cost",
        ),
        migrations.AddField(
            model_name="issuerec",
            name="i_cost",
            field=models.FloatField(
                default=0.0, max_length=50, verbose_name="issue_cost"
            ),
        ),
    ]
