# Generated by Django 5.0.6 on 2024-06-30 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0003_issuecomment_c_cont_alter_issueowner_profile_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="o_uid",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="issueowner",
                to="issues.issueowner",
            ),
        ),
    ]
