# Generated by Django 4.2.7 on 2024-06-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("issues", "0003_change_structure_3"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="i_desc",
            field=models.CharField(blank=True, default="No desc", max_length=512),
        ),
    ]
