# Generated by Django 5.0.6 on 2024-07-02 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0004_alter_issue_o_uid"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="issue",
            options={"ordering": ["-i_date"]},
        ),
        migrations.AlterField(
            model_name="issue",
            name="o_uid",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.PROTECT,
                to="issues.issueowner",
            ),
        ),
        migrations.AlterField(
            model_name="issuecomment",
            name="commenter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="issues.issueowner",
            ),
        ),
        migrations.AlterField(
            model_name="issuecomment",
            name="issue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="issues.issue"
            ),
        ),
        migrations.AlterField(
            model_name="issuerec",
            name="s_uid",
            field=models.ForeignKey(
                default=2,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="issues.issueowner",
            ),
        ),
    ]
