# Generated by Django 4.2.7 on 2024-06-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("issues", "0004_change_structure_4"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="i_status",
            field=models.BooleanField(
                choices=[(False, "Not solved"), (True, "Solved")],
                default=False,
                verbose_name="Solve status",
            ),
        ),
    ]
