# Generated by Django 5.0.6 on 2024-07-04 14:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0005_alter_issue_options_alter_issue_o_uid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issue",
            name="s_date",
        ),
        migrations.AddField(
            model_name="issuerec",
            name="s_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="solved_date"
            ),
        ),
        migrations.AlterField(
            model_name="issueowner",
            name="pts",
            field=models.IntegerField(default=100, verbose_name="UserPoints"),
        ),
    ]
